version: "3.9"

services:
  django:
    build:
      context: .
      args:
       - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./django_meconomics:/django_meconomics
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=maris
      - DB_PASS=bv4811ss
    depends_on:
      - db

  db:
    image: postgres:16-alpine3.18
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=maris
      - POSTGRES_PASSWORD=bv4811ss

volumes:
  dev-db-data:
