version: "3.9"

services:
  django:
    build:
      context: .
      args:
       - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./django_meconomics:/django_meconomics
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
