# Generated by Django 4.2.6 on 2023-10-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_acions_per_day_appsettings_actions_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='settings_number',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
