# Generated by Django 4.2.6 on 2023-10-14 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.PositiveIntegerField()),
                ('name_low', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=254)),
                ('warehouse', models.BooleanField(default=True)),
                ('registration_number', models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('established', models.DateField()),
                ('invoice_prefix', models.CharField(max_length=2, unique=True)),
                ('manufacturer_code', models.IntegerField(blank=True, default=0)),
                ('street_adress_1', models.IntegerField(blank=True, default=0)),
                ('street_adress_2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('post_code', models.CharField(blank=True, max_length=6)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('employee_count', models.IntegerField(blank=True)),
                ('total_salaries_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_bruto_salaries', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_salary_vsaoi_dd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_salary_vsaoi_dn', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_salary_iin', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_salary_netto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('average_salary_brutto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('owner_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('parent_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_companies', to='companies.company')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
