# Generated by Django 4.2.6 on 2023-10-14 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('companies', '0002_alter_company_owner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employee_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('citizen', 'company')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='company',
            name='registration_number',
            field=models.BigIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
