# Generated by Django 4.2.6 on 2023-10-14 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0006_remove_citizen_companies'),
        ('companies', '0003_alter_company_employee_count_alter_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='parent_company',
            new_name='owner_com',
        ),
        migrations.RemoveField(
            model_name='company',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='company',
            name='owner_pp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_companies', to='citizens.citizen'),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner_type',
            field=models.CharField(choices=[('0', 'Private'), ('1', 'Company'), ('2', 'Government Institution')], default='0', max_length=10),
        ),
    ]
