# Generated by Django 4.2.6 on 2023-10-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_name_alter_company_name_low'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='street_adress_1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
