# Generated by Django 4.2.6 on 2023-10-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_company_street_adress_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='post_code',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
