# Generated by Django 4.2.6 on 2023-10-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_company_post_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_low', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=254)),
                ('registration_number', models.BigIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('established', models.DateField()),
                ('street_adress_1', models.IntegerField(blank=True, null=True)),
                ('street_adress_2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('post_code', models.CharField(blank=True, max_length=7)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('employee_count', models.IntegerField(blank=True)),
                ('total_salaries_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_bruto_salaries', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_salary_vsaoi_dd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_salary_vsaoi_dn', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_salary_iin', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_salary_netto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('average_salary_brutto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'verbose_name_plural': 'Government Institutions',
            },
        ),
    ]
