# Generated by Django 4.2.6 on 2023-10-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_govinstitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='govinstitution',
            name='authority',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
