# Generated by Django 4.2.6 on 2023-10-16 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_govinstitution_authority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='owner_type',
            new_name='owner_type_low',
        ),
    ]
