# Generated by Django 4.2.6 on 2023-10-18 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0009_alter_citizen_post_code'),
        ('companies', '0010_rename_owner_type_company_owner_type_low'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=254)),
                ('salary_brutto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('salary_vsaoi_dd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('salary_vsaoi_dn', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('salary_iin', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('salary_netto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='companies.company')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='citizens.citizen')),
            ],
        ),
    ]
