# Generated by Django 4.2.7 on 2023-11-12 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_govinstemployees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='warehouse', max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=254)),
                ('warehouse_code', models.CharField(blank=True, default='0', max_length=6)),
                ('street_adress_1', models.IntegerField(blank=True, default=0)),
                ('street_adress_2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('post_code', models.CharField(blank=True, max_length=6)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_owner', to='companies.company')),
            ],
        ),
    ]
