# Generated by Django 4.2.7 on 2023-11-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='display_name',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='name_low',
            field=models.CharField(blank=True, default='warehouse', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
