# Generated by Django 4.2.6 on 2023-10-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('first_name', models.CharField(max_length=254)),
                ('first_name_display', models.CharField(blank=True, max_length=254, null=True)),
                ('last_name', models.CharField(max_length=254)),
                ('last_name_display', models.CharField(blank=True, max_length=254, null=True)),
                ('bsn_number', models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('street_adress_1', models.IntegerField(blank=True, default=0, null=True)),
                ('street_adress_2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('post_code', models.CharField(blank=True, max_length=6)),
                ('country', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Citizens',
            },
        ),
    ]
