# Generated by Django 4.2.6 on 2023-10-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0003_remove_citizen_first_name_display_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='street_adress_1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
