# Generated by Django 4.2.6 on 2023-10-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('citizens', '0004_alter_citizen_street_adress_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='citizens', to='companies.company'),
        ),
    ]
