# Generated by Django 4.2.6 on 2023-10-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0007_remove_citizen_first_name_low_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='full_name',
            field=models.CharField(blank=True, editable=False, max_length=254, null=True),
        ),
    ]
